-- DropTable
DROP TABLE IF EXISTS "Reaction" CASCADE;
DROP TABLE IF EXISTS "MediaAttachment" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "Conversation" CASCADE;
DROP TABLE IF EXISTS "Friendship" CASCADE;
DROP TABLE IF EXISTS "Block" CASCADE;
